services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.14
    container_name: etcd
    command: >
      /usr/local/bin/etcd
      --name s1
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd:2380
      --initial-cluster s1=http://etcd:2380
      --initial-cluster-state new
      --initial-cluster-token dev-etcd
      --log-level info
    ports:
      - "2379:2379"
    volumes:
      - ./etcd-data:/etcd-data
    healthcheck:
      test: ["CMD", "etcdctl", "--endpoints=http://127.0.0.1:2379", "endpoint", "health"]
      interval: 10s
      timeout: 3s
      retries: 5
    environment:
      - ETCDCTL_API=3
volumes:
  etcd-data: {}